// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DemoPOS.Models
{
    [Table("Order")]
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public Guid OrderId { get; set; }
        [StringLength(150)]
        public string OrderName { get; set; }
        [StringLength(36)]
        public string CardId { get; set; }
        [StringLength(16)]
        public string PhoneNo { get; set; }
        [StringLength(150)]
        public string Address1 { get; set; }
        [StringLength(150)]
        public string Address2 { get; set; }
        [StringLength(150)]
        public string Province { get; set; }
        [StringLength(150)]
        public string District { get; set; }
        [StringLength(150)]
        public string Subdistrict { get; set; }
        [StringLength(10)]
        public string ZipCode { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? Subtotal { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? Total { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }

        [InverseProperty(nameof(OrderDetail.Order))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}