// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DemoPOS.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public Guid ProductId { get; set; }
        public Guid ProductGroupId { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? Price { get; set; }
        public DateTime? ExpiryDate { get; set; }
        [StringLength(500)]
        public string Thumbnail { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(ProductGroupId))]
        [InverseProperty("Products")]
        public virtual ProductGroup ProductGroup { get; set; }
        [InverseProperty(nameof(OrderDetail.Product))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}